export const SET_ALL_STUDIES = "SET_ALL_STUDIES";
export const SET_REFRESH_MODAL = "SET_REFRESH_MODAL";
export const SET_IS_LOGIN = "SET_IS_LOGIN";
export const SET_CURRENT_STUDY = "SET_CURRENT_STUDY";
export const UPDATE_CURRENT_STUDY = "UPDATE_CURRENT_STUDY";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_PUBLIC_STUDIES = "SET_PUBLIC_STUDIES";
export const SET_SURVEY_LINK = 'SET_SURVEY_LINK';
export const SET_SURVEY_QUEUE_LINK = 'SET_SURVEY_QUEUE_LINK';
export const SET_SURVEY_STATUS = 'SET_SURVEY_STATUS';
export const SET_ATTRS_ORDER = "SET_ATTRS_ORDER";
export const UPDATE_ATTRS_ORDER = "UPDATE_ATTRS_ORDER";

